// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8y8RVanTS8SBaazxnATE5Ea9S17pXvKM',
    appId: '1:464701040005:web:8b1bbfc349926d481a10ec',
    messagingSenderId: '464701040005',
    projectId: 'diplom-23056',
    authDomain: 'diplom-23056.firebaseapp.com',
    databaseURL: 'https://diplom-23056-default-rtdb.firebaseio.com',
    storageBucket: 'diplom-23056.firebasestorage.app',
    measurementId: 'G-53YZV8218V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJXgVmPFF5Hxqqy29cuUudzhwnKkZxCyA',
    appId: '1:464701040005:android:52cfd4c10c6f83b11a10ec',
    messagingSenderId: '464701040005',
    projectId: 'diplom-23056',
    databaseURL: 'https://diplom-23056-default-rtdb.firebaseio.com',
    storageBucket: 'diplom-23056.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnCethkf75G5keoANm3GKLJb4Yh2Bm9P0',
    appId: '1:464701040005:ios:f4c2aed6a31ba9e11a10ec',
    messagingSenderId: '464701040005',
    projectId: 'diplom-23056',
    databaseURL: 'https://diplom-23056-default-rtdb.firebaseio.com',
    storageBucket: 'diplom-23056.firebasestorage.app',
    iosBundleId: 'com.example.jvgeeDiplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnCethkf75G5keoANm3GKLJb4Yh2Bm9P0',
    appId: '1:464701040005:ios:f4c2aed6a31ba9e11a10ec',
    messagingSenderId: '464701040005',
    projectId: 'diplom-23056',
    databaseURL: 'https://diplom-23056-default-rtdb.firebaseio.com',
    storageBucket: 'diplom-23056.firebasestorage.app',
    iosBundleId: 'com.example.jvgeeDiplom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8y8RVanTS8SBaazxnATE5Ea9S17pXvKM',
    appId: '1:464701040005:web:81354736644084831a10ec',
    messagingSenderId: '464701040005',
    projectId: 'diplom-23056',
    authDomain: 'diplom-23056.firebaseapp.com',
    databaseURL: 'https://diplom-23056-default-rtdb.firebaseio.com',
    storageBucket: 'diplom-23056.firebasestorage.app',
    measurementId: 'G-FGX1GWMXM7',
  );

}